#!/bin/bash
clear
echo "----------------------------------------------"
METAFILE="xMusic.meta"
FILEDIR="Youtube"
APPDIR="xm"
####################################################################
PREFIX="/home/"$(echo $USER)"/"$(echo $APPDIR)"/"$(echo $FILEDIR)
TARGET="/*"
MURL="/home/"$(echo $USER)"/"$(echo $APPDIR)"/"$(echo $FILEDIR)"/"$(echo $METAFILE)
cd $APPDIR
cd $FILEDIR
T=$(echo $PREFIX$TARGET)
echo "Entering $FILEDIR User Libary"
###################################################################
xFolder=$(ls -d $T)
###################################################################
echo "----------------------------------------------"
echo "Searching for Folders"
echo "----------------------------------------------"
echo "----------------------------------------------"
echo "Wiping Youtube Libary Metafile"
echo "----------------------------------------------"
echo "Metafile: $MURL"
echo "----------------------------------------------"
cat "$MURL"
echo "----------------------------------------------"
echo "## Cleaned" > "$MURL"
echo "----------------------------------------------"
cat "$MURL"
echo "----------------------------------------------"
###################################################################
for folder in `echo $xFolder`; do
##############################
if [ ! -d "$folder" ]; then
echo ""
echo "No More Folders to List!"
echo ""
echo "==================================="
exit;

else
##############################
sleep 0.2
echo "Folder: "${folder#$PREFIX}
sleep 0.2
echo "File: "${folder#$PREFIX}${folder#$PREFIX}".mp3"
sleep 0.2
exit;
fi

##############################
done
###################################################################
echo "----------------------------------------------"
###################################################################
