#!/bin/bash
clear
sleep 0.3
echo "-----------------------------------------------"
echo "Setting up XM Script Directory"
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
dir="/home/"$USER"/xm/Youtube/"
file="xMusic.meta"
echo $dir$file
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
echo "Creating Directorys and Configuration File"
mkdir -p $dir
cd $dir
touch $file
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
echo "Folder: "$dir  " has been created. "
echo "File: "$file " has been created. "
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
echo "$file has been created!"
echo "## File Created!" > "./$file"
echo "-----------------------------------------------"
cat "./$file"
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
cd "/home/$USER/xm/"
echo "Entering /home/$USER/xm/ "
echo "-----------------------------------------------"
sleep 0.2
echo "-----------------------------------------------"
ls
echo "-----------------------------------------------"
sleep 0.3
echo "-----------------------------------------------"
echo "Directorys Made"
echo "-----------------------------------------------"
